# Generated by Django 4.2.4 on 2023-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogenquiry',
            name='blog_file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Blog_images'),
        ),
    ]
